# Generated by Django 5.2.7 on 2025-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('useremail', models.EmailField(max_length=254, null=True)),
                ('userage', models.IntegerField(null=True)),
                ('upload', models.FileField(null=True, upload_to='image')),
                ('discription', models.CharField(max_length=150)),
            ],
        ),
    ]
