# Generated by Django 5.2.7 on 2025-12-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='data',
        ),
    ]
