# Generated by Django 5.2.7 on 2025-12-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_info_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='data',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
