# Generated by Django 5.2.7 on 2025-12-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_data_photo_data_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='cpassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
