# Generated by Django 5.2.7 on 2025-12-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_data_cpassword_data_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='upload',
        ),
    ]
