# Generated by Django 5.2.7 on 2025-12-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_data_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='photo',
        ),
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
