# Generated by Django 5.2.7 on 2025-12-29 08:10

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_data_photo_data_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='cpassword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='discription',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[app.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='data',
            name='password',
            field=models.CharField(default='null', max_length=50, validators=[app.models.validate_password]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[app.models.validate_resume_file]),
        ),
        migrations.AlterField(
            model_name='data',
            name='userage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='useremail',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(max_length=50, null=True, validators=[app.models.validate_username, django.core.validators.MinLengthValidator(3)]),
        ),
    ]
