# Generated by Django 5.2.7 on 2026-01-03 17:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_upload_alter_data_cpassword_alter_data_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='photo',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/'),
        ),
    ]
